api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/git"
  id = "initializ-buildpacks/git"
  name = "Intitializ Buildpack for Git"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
